version: '3'
services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube_docker_image_2
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    networks:
      - jenkinsnet

volumes:
  sonarqube_data:

networks:
  jenkinsnet: